server:
  port: 8761
  
eureka:
    instance:
        hostname: ${app.hostname}
    client:
        registerWithEureka: false
        fetchRegistry: false
        server:
            waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/