spring:
    application:
        name: supplier-resource
    data:
       mongodb:
           uri: mongodb://localhost:27017/tercerizzario
---
app:
    datasource:
        url: jdbc:mongodb://localhost:27017/auth
        pool-size: 30
--- 
server:
    port: ${PORT}
---    
eureka:
    instance:
        hostname: ${app.hostname}
    leaseRenewalIntervalInSeconds: 5
    metadataMap: 
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    client:
      healthcheck:
        enabled: true
      registerWithEureka: false
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:8761/eureka/