spring:
    application:
        name: supplier-resource
    
        
server:
    port: 7111
    
eureka: 
  client: 
      registerWithEureka: true
      serviceUrl:
        defaultZone: http://${HOSTNAME}:localhost:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
