zuul:
    ignoreServices: "*"
    routes:
        supplier-resource:
            path: /suppliers/**
            url: http://localhost:7111/suppliers
ribbon:
    eureka:
        enabled: false
        
server:
    port: 8080
    
#eureka:
#    serviceUrl:
#        default=http://localhost:8761/eureka/

supplier-resource:
    ribbon:
        listOfServers: http://localhost:7111/
        
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG        

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
