spring:
    application:
        name: profession-resource
    data:
       mongodb:
           uri: mongodb://localhost:27017/tercerizzario
               
server:
    port: 7211
    
eureka: 
  client: 
      registerWithEureka: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
